# Generated by Django 3.0.4 on 2020-04-18 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
                ('theme_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.IntegerField(default=1)),
                ('discount_price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
